name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: engineerd/setup-minikube@v1

    - name: Start Minikube
      run: minikube start

    - name: Deploy to Minikube
      run: kubectl apply -f deployment.yaml

    - name: Clean up Minikube
      run: minikube stop
